### ISSUE TITLE
Any idea's to implement Dagger-Hilt Dependency injection

### ISSUE THREAD

**Issue by MubarakNative** [eric-ampire/android-clean-architecture#1]
@eric-ampire

**Comment by eric-ampire** [comment]
There's a video I've created on that https://m.youtube.com/watch?v=jR8LWSox520

**Comment by MubarakNative** [comment]
Can i contribute this project to implement Dagger-Hilt DI and you also need to add license for this project

**Comment by eric-ampire** [comment]
Sure go ahead

**Comment by MubarakNative** [comment]
Before any contribution to any repositories, that project needs a license. Without a license it becomes proprietary to you only. i can't add a new feature to this Project. 

https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/licensing-a-repository
